backup_location: "/media/$USER/backup/backups"  
copy_timeout: 60  # Timeout for copying each file in seconds
exclude_directory_names:
  - ".cache"  
  - ".steam"
  - ".steampath"
  - ".steampid"
  - ".ollama"
  - ".conda"
  - ".condarc"
  - ".dotnet"
  - ".steampath"  
  - "snap"
  - "venv"
  - ".venv"
  - "datasets"
  - "dataset"
  - "artifacts"
  - ".zoom"
  - "anaconda3"
  - ".modelsim"
  - "opt"
  - ".local"
  - ".mono"
